### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AANihad** [AANihad/TP_Compile#1]
- [x] **Analyse Lexicale**.
- [x] **Analyse syntaxique**.
- [x] **Analyse sémantique** (Listener).
	- [x] Table des symboles
		- [x] Créer une classe ligne
		- [x] Créer une structure valeur
		- [x] Calculer les valeurs des expression
		- [x] Implémenter les méthodes
	- [x] Routines TS.
		- [x] E/S Programme.
			- [x] Insertion dans la TS.
		- [x] E/S Declaration.
			- [x] Empêcher les doubles déclarations.
		- [x] E/S Exp.
			- [x] Tester la compatibilité des types.
			- [x] Empêcher l'utilisation des variables non déclarées.
		- [x] E/S Affectation.
			- [x] Tester la compatibilité des types.
			- [x] Empêcher l'utilisation des variables non déclarées.
		- [x] Compatibilité des types d'expression .
		- [x] Type du résultat.
	- [ ] Gestion des Erreurs.
		- [x] Ajouter des try catch dans chaque routine.
		- [x] Ajouter un compteur de lignes
		- [x] Ajouter des Errors Listeners
		- [x] incompatibilité des types
		- [x] division par 0
		- [x] Double déclaration
		- [x]  idf non déclaré
		- [x]  spécifier le type de l'erreur 
		- [x]  Instanciation d'une variable
- [x] **Génération de la forme intermédiaire**
	- [x]  Classe TableQuad
		- [x]  Classe Quadruplet
	- [x]  Classe RoutinesQuad.
		- [x] Instructions arithmétique.
		- [x] Instructions de branchement.
		- [x] Branchement conditionnel (Instruction ***IF ELSE***)
		- [x] Instruction ***LIRE***.
		- [x] Instruction ***ECRIRE***.
- [x] **Génération de code objet**
	- [x]  Quad to Assembler
		- [x]  ADD/SUB/DIV/MUL
		- [x]  Read
		- [x]  Write
		- [x]  Branchments conditionnels
		- [x]  Branchement inconditionnels
		- [x]  Affectation
